### ISSUE TITLE
[Suggestion] Implement an API

### ISSUE THREAD

**Issue by mcmdev** [PluginBugs/Issues-ScratchIt#1]
**Is your feature request related to a problem? Please describe.**
Most plugins with unique features are hard and clunky to intergrate into larger, well thought out network systems e.g. a hub reward system

**Describe the solution you'd like**
An API which can access various features, like:
- Opening a scratch card for a player
- Closing a scratch card for a player
- Maybe even dynamically create cards?

**Describe alternatives you've considered**
Executing commands as the player, very bad solution.

**Comment by LoneDev6** [comment]
Amazing idea! I will implement this in the next days.

Dynamically creating cards with API would be a bit complex to manage both for the dev who uses the API both for me, I may integrate that in the future if more information of the possible usage would be included in the request as for now I don't really have an idea on how to structure the whole feature.

Thanks for the ideas :D

**Comment by LoneDev6** [comment]
https://scratchit.devs.beer/developers/java-api
