### ISSUE TITLE
Maps dont load [BUG] 

### ISSUE THREAD

**Issue by Mdsh9** [PluginBugs/Issues-ScratchIt#14]
**Describe the bug**
When i open a Scratch map, dont appears the content of the map, like a empty map, but the game works.
**To Reproduce**
1. Get any Scratch Map
2. Then you open with right click
3.  Now the map its Empty and dont show anything

**Expected behavior**

**Screenshots**
![image](https://user-images.githubusercontent.com/113609845/191878767-bcdf6189-9c84-40ce-a7c5-147c09014821.png)
**Info (please complete the following information):**
 - Server version: Paper 1.19.2
 - Client version: Lunar Client 1.19.2
 - Plugin version: Scratchit 1.1.19-r1

**Additional context**
 Video of the error: https://imgur.com/qj0cavt

My plugins are these:
Plugins (77): AdvancedEnchantments, AnimatedScoreboard, AntiJoinLeaveMessages, BedrockPlayerManager, BlueSlimeCore (SirBlobmanAPI, SirBlobmanCore, XSeries), BoomBox, Cartographer2, ccInstantRespawn, ChestSort, Chunky, Citizens, CMILib, CombatLogX, CommandPanels, ConditionalEvents, ConditionalTextPlaceholders, CrossplatForms, CustomCommands, DecentHolograms, EasyClearChat, Emailer*, Essentials, EssentialsChat, EssentialsDiscord, EssentialsProtect, EssentialsSpawn, Factions, floodgate, GCore, GPS, Graves, HeadDatabase, HealthBar, ItemEdit, ItemTag, Jobs, KGenerators, LagAssist, LibsDisguises, LoneLibs, LootChest, LPC, LuckPerms, MineableSpawners, Multiverse-Core, MythicMobs, NexEngine, NoteBlockAPI, NoteBlockMusicPlayer, PL-Hide, PlaceholderAPI, PlayerKits, PlayerVaults, PocketGames, ProtocolLib, Rankup, SafariNet, ScratchIt, SellGUI, Shopkeepers, SimplePortals, SkinsRestorer, Spartan, TabList, TradeSystem, UltimateAutoRestart, UltimateTNT, UltraBar, Vault, VoidGen, Votifier, VotifierPlus, VotingPlugin, WorldEdit, WorldGuard, YamipaPlugin, zAuctionHouseV3.

**Comment by LoneDev6** [comment]
You are using a custom client, please try to join using vanilla Minecraft and let me know.

also send a full server log of when the issue occurred.

**Comment by Mdsh9** [comment]
Thank you for the response, i try it with a Vanilla Client, but still dont work , i create another video of the error.

Video of the error: https://imgur.com/mw011Zu

Server version: Paper 1.19.2
Client version: Vanilla Client 1.19.2
Plugin version: Scratchit 1.1.19-r1

My plugins are these:
Plugins (77): AdvancedEnchantments, AnimatedScoreboard, AntiJoinLeaveMessages, BedrockPlayerManager, BlueSlimeCore (SirBlobmanAPI, SirBlobmanCore, XSeries), BoomBox, Cartographer2, ccInstantRespawn, ChestSort, Chunky, Citizens, CMILib, CombatLogX, CommandPanels, ConditionalEvents, ConditionalTextPlaceholders, CrossplatForms, CustomCommands, DecentHolograms, EasyClearChat, Emailer*, Essentials, EssentialsChat, EssentialsDiscord, EssentialsProtect, EssentialsSpawn, Factions, floodgate, GCore, GPS, Graves, HeadDatabase, HealthBar, ItemEdit, ItemTag, Jobs, KGenerators, LagAssist, LibsDisguises, LoneLibs, LootChest, LPC, LuckPerms, MineableSpawners, Multiverse-Core, MythicMobs, NexEngine, NoteBlockAPI, NoteBlockMusicPlayer, PL-Hide, PlaceholderAPI, PlayerKits, PlayerVaults, PocketGames, ProtocolLib, Rankup, SafariNet, ScratchIt, SellGUI, Shopkeepers, SimplePortals, SkinsRestorer, Spartan, TabList, TradeSystem, UltimateAutoRestart, UltimateTNT, UltraBar, Vault, VoidGen, Votifier, VotifierPlus, VotingPlugin, WorldEdit, WorldGuard, YamipaPlugin, zAuctionHouseV3.

**Comment by Mdsh9** [comment]
[latest.log](https://github.com/PluginBugs/Issues-ScratchIt/files/9635441/latest.log)
This is my last log in the server. @LoneDev6

**Comment by LoneDev6** [comment]
The strange thing is that I cannot reproduce the issue with the latest 1.19.2 Paper and the vanilla 1.19.2 client.

```
This server is running Paper version git-Paper-174 (MC: 1.19.2) (Implementing API version 1.19.2-R0.1-SNAPSHOT) (Git: 01a1387)

ProtocolLib version 5.0.0-SNAPSHOT-b586


```



https://user-images.githubusercontent.com/27242001/192303366-19dde5c1-15aa-4c0e-b309-52c3d87a64bc.mp4

**Comment by Mdsh9** [comment]
I think it could be problem with some plugins that use maps, it could be a incompability issue maybe.
List of Plugins that use maps:
- Cartographer2
- LagAssist
- YamipaPlugin
and of course
- ScratchIt

If that is the case, What can i do?

**Comment by LoneDev6** [comment]
Remove them, test the plugin.
