### ISSUE TITLE
[BUG] 100% WIN CHANCE GLITCH

### ISSUE THREAD

**Issue by Wastinqs** [PluginBugs/Issues-ScratchIt#16]
**Describe the bug**
Players can glitch the scratch cards to get 100% win chance. Check screenshot.

**To Reproduce**
1. Scratch something
2. See that you'll lose
3. Immidiately exit the game
4. Get another chance

**Expected behavior**
-

**Screenshots**
![bug](https://user-images.githubusercontent.com/110524899/194757073-63085dd6-e08b-484c-8b67-02ff79eaeb3d.png)

**Info (please complete the following information):**
 - Server version: paper 1.17.1
 - Client version: optifine 1.17.1
 - Plugin version: 1.1.19-r3

**Additional context**
- Please fix asap

**Comment by LoneDev6** [comment]
The plugin should already make you instantly win if you start scratching and leave the server.
Can you make a video?

**Comment by Wastinqs** [comment]
https://www.youtube.com/watch?v=QMS9KXbUjEA

The user has 4 scratchcards (native name: diamonds) on him and starts to scratch it. Once found out he's about to lose he quits and re-joins and still has 4 cards to go.
