### ISSUE TITLE
[BUG] When starting scrathing

### ISSUE THREAD

**Issue by Ryzz3nn** [PluginBugs/Issues-ScratchIt#20]
**Describe the bug**
When you start scrathing "scratch_and_win" it will kick you 

**To Reproduce**
1. Start scrathing "scratch_and_win"

**Expected behavior**
When scrathcing "scratch_and_win" it will let you scratch it without getting kicked

**Screenshots**
https://streamable.com/uidy2w

**Info (please complete the following information):**
 - Server version: Paper 1.19.3 (git-Paper-386 (MC: 1.19.3)
 - Client version: fabric 1.19.2 (tested with both vanilla 1.19.2 1.19.3)
 - Plugin version: 1.1.19-r5
**Additional context**
this happened after i updated to 1.19.3 to fix a few other issues with our server

**Comment by LoneDev6** [comment]
It should have been fixed in the upcoming update.
I tested and I don't get kicked anymore on 1.19.3
