### ISSUE TITLE
[BUG] 

### ISSUE THREAD

**Issue by Ange5e** [PluginBugs/Issues-ScratchIt#21]
**Describe the bug**
The bug appears when I do the first right click (in game) for interact with the items of plugin.

**To Reproduce**
1. I take the item from gui of plugin opened by the command /scratchit list
2. I'll click a right click on item for interact with that. 
3. The plugin print an error on console.

**Screenshots**
![image](https://user-images.githubusercontent.com/112621339/228624982-77efdcc9-692c-4cb5-ae9f-38b2fd717922.png)

**Info (please complete the following information):**
 - Server version: paper 1.12.2
 - Plugin version: 1.1.19-r6

**Comment by LoneDev6** [comment]
Please do not share errors as screenshots.
Next time provide the error text and the full log if possible.

Anyway you seem to have a corrupted JAR.
Redownload it.
