### ISSUE TITLE
Errors in console after update

### ISSUE THREAD

**Issue by wynter1978** [PluginBugs/Issues-ScratchIt#7]
29.03 13:38:52 [Server] INFO Detected ItemsAdder
29.03 13:38:52 [Server] INFO Detected PlaceholderAPI
29.03 13:38:52 [Server] INFO Waiting ItemsAdder to register custom items...
29.03 13:38:52 [Server] WARN java.lang.IllegalThreadStateException
29.03 13:38:52 [Server] WARN at dev.lone.ScratchIt.main.H.a(class:2241)
29.03 13:38:52 [Server] WARN at dev.lone.ScratchIt.main.H.a(class:3157)
29.03 13:38:52 [Server] WARN at dev.lone.ScratchIt.main.cs.a(class:1668)
29.03 13:38:52 [Server] WARN at dev.lone.ScratchIt.main.bI.a(class:9063)
29.03 13:38:52 [Server] WARN at dev.lone.ScratchIt.main.Z.a(class:6300)
29.03 13:38:52 [Server] WARN at dev.lone.ScratchIt.main.m.a(class:4057)
29.03 13:38:52 [Server] WARN at dev.lone.ScratchIt.main.aw.a(class:344)
29.03 13:38:52 [Server] WARN at dev.lone.ScratchIt.main.l.a(class:1356)
29.03 13:38:52 [Server] WARN at dev.lone.ScratchIt.main.w.a(class:3437)
29.03 13:38:52 [Server] WARN at dev.lone.ScratchIt.main.V.a(class:7671)
29.03 13:38:52 [Server] WARN at dev.lone.ScratchIt.main.aQ.a(class:4328)
29.03 13:38:52 [Server] WARN at dev.lone.ScratchIt.main.bi.a(class:5179)
29.03 13:38:52 [Server] WARN at dev.lone.ScratchIt.main.aC.a(class:5946)
29.03 13:38:52 [Server] WARN at dev.lone.ScratchIt.main.W.a(class:5588)
29.03 13:38:52 [Server] WARN at dev.lone.ScratchIt.main.E.a(class:9259)
29.03 13:38:52 [Server] WARN at dev.lone.ScratchIt.main.bT.a(class:4167)
29.03 13:38:52 [Server] WARN at dev.lone.ScratchIt.main.w.a(class:8987)
29.03 13:38:52 [Server] WARN at dev.lone.ScratchIt.main.i.a(class:8546)
29.03 13:38:52 [Server] WARN at dev.lone.ScratchIt.main.bZ.a(class:3354)
29.03 13:38:52 [Server] WARN at dev.lone.ScratchIt.main.aW.a(class:7668)
29.03 13:38:52 [Server] WARN at dev.lone.ScratchIt.main.az.a(class:7938)
29.03 13:38:52 [Server] WARN at dev.lone.ScratchIt.h.a(class:6991)
29.03 13:38:52 [Server] WARN at dev.lone.ScratchIt.main.bD.a(class:4676)
29.03 13:38:52 [Server] WARN at dev.lone.ScratchIt.main.cB.a(class:8422)
29.03 13:38:52 [Server] WARN at dev.lone.ScratchIt.main.U.a(class:7261)
29.03 13:38:52 [Server] WARN at dev.lone.ScratchIt.main.ag.a(class:2283)
29.03 13:38:52 [Server] WARN at dev.lone.ScratchIt.main.a.a(class:3230)
29.03 13:38:52 [Server] WARN at dev.lone.ScratchIt.main.bS.a(class:5611)
29.03 13:38:52 [Server] WARN at dev.lone.ScratchIt.main.bP.a(class:6360)
29.03 13:38:52 [Server] WARN at dev.lone.ScratchIt.main.H.a(class:115)
29.03 13:38:52 [Server] WARN at dev.lone.ScratchIt.main.Y.a(class:8080)
29.03 13:38:52 [Server] WARN at dev.lone.ScratchIt.main.cc.a(class:3546)

29.03 13:38:52 [Server] WARN at dev.lone.ScratchIt.api.CustomCardRenderer.a(class:8643)
29.03 13:38:52 [Server] WARN at dev.lone.ScratchIt.main.aw.a(class:5246)
29.03 13:38:52 [Server] WARN at dev.lone.ScratchIt.main.d.a(class:1319)
29.03 13:38:52 [Server] WARN at dev.lone.ScratchIt.main.aI.a(class:934)
29.03 13:39:14 [Server] WARN java.lang.IllegalThreadStateException
29.03 13:39:14 [Server] WARN at dev.lone.ScratchIt.main.bI.a(class:1525)
29.03 13:39:14 [Server] WARN at dev.lone.ScratchIt.main.bP.a(class:898)
29.03 13:39:14 [Server] WARN at dev.lone.ScratchIt.main.a.a(class:3884)
29.03 13:39:14 [Server] WARN at dev.lone.ScratchIt.main.ci.a(class:7986)
29.03 13:39:14 [Server] WARN at dev.lone.ScratchIt.main.aK.a(class:715)
29.03 13:39:14 [Server] WARN at dev.lone.ScratchIt.main.bQ.a(class:7683)
29.03 13:39:14 [Server] WARN at dev.lone.ScratchIt.main.cD.a(class:795)
29.03 13:39:14 [Server] WARN at dev.lone.ScratchIt.main.aq.a(class:9549)
29.03 13:39:14 [Server] WARN at dev.lone.ScratchIt.main.bu.a(class:4596)
29.03 13:39:14 [Server] WARN at dev.lone.ScratchIt.main.o.a(class:5489)
29.03 13:39:14 [Server] WARN at dev.lone.ScratchIt.main.ci.a(class:6862)
29.03 13:39:14 [Server] WARN at dev.lone.ScratchIt.main.bg.a(class:9169)
29.03 13:39:14 [Server] WARN at dev.lone.ScratchIt.main.aw.a(class:4687)
29.03 13:39:14 [Server] WARN at dev.lone.ScratchIt.main.bV.a(class:813)

**Info (please complete the following information):**
 - Server version: 1.18.2
 - Client version: paper/spigot (up to date)
 - Plugin version: (Scratchit_1.1.14)

**Additional context**
When I updated my plugins this error is now coming up in the console. I am still learning and sorry if this is something really easy to fix. Thanks for your help! :D

**Comment by L3v3lup** [comment]
I have this error aswell.

**Comment by LoneDev6** [comment]
Delete the `ScratchIt\storage` folder and try to restart, seems cache is corrupted for some reason.
